// Package dktypes 定义领域知识层（Domain Knowledge Layer）中所有跨包共享的核心类型、
// 枚举、数据结构及其校验方法。
//
// 本文件包含知识图谱的核心数据结构：Node、Edge、Subgraph 以及与冲突检测和交叉引用
// 相关的 CrossReference 和 ConflictReport 结构体。
package dktypes

import "time"

// ——————————————————————————————————————————————————————————————————————————————
// Node — 知识图谱节点
// ——————————————————————————————————————————————————————————————————————————————

// Node 表示知识图谱中的一个节点（实体或概念），对应数据库 nodes 表的一行。
// Node represents a single node in the knowledge graph (entity or concept),
// corresponding to one row in the database nodes table.
type Node struct {
	// ID 是节点的唯一标识符。
	// ID is the unique identifier of the node.
	ID string `json:"id" yaml:"id"`
	// Label 表示节点标签类型：Entity 或 Concept。
	// Label indicates the node label type: Entity or Concept.
	Label Label `json:"label" yaml:"label"`
	// Name 是节点的可读名称。
	// Name is the human-readable name of the node.
	Name string `json:"name" yaml:"name"`
	// Summary 是节点的简短摘要描述。
	// Summary is a short summary description of the node.
	Summary string `json:"summary" yaml:"summary"`
	// Synonyms 是节点名称的同义词列表（以逗号分隔的字符串）。
	// Synonyms is a comma-separated list of synonyms for the node name.
	Synonyms string `json:"synonyms,omitempty" yaml:"synonyms,omitempty"`
	// Domain 是节点所属的业务域。
	// Domain is the business domain to which the node belongs.
	Domain string `json:"domain" yaml:"domain"`
	// Subdomain 是节点所属的业务子域。
	// Subdomain is the business subdomain to which the node belongs.
	Subdomain string `json:"subdomain" yaml:"subdomain"`
	// Description 是节点的详细描述。
	// Description is a detailed description of the node.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Properties 是以 JSON 字符串存储的节点附加属性。
	// Properties is a JSON string containing additional node properties.
	Properties string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Tags 是以逗号分隔的节点标签列表。
	// Tags is a comma-separated list of tags for the node.
	Tags string `json:"tags,omitempty" yaml:"tags,omitempty"`
	// RelatedEntities 是以逗号分隔的关联实体 ID 列表。
	// RelatedEntities is a comma-separated list of related entity IDs.
	RelatedEntities string `json:"related_entities,omitempty" yaml:"related_entities,omitempty"`
	// Confidence 表示节点数据的置信度（0.0 ~ 1.0）。
	// Confidence is the confidence score of the node data (0.0 to 1.0).
	Confidence float64 `json:"confidence" yaml:"confidence"`
	// Provenance 表示节点数据的来源方式。
	// Provenance indicates how the node data was sourced.
	Provenance Provenance `json:"provenance" yaml:"provenance"`
	// SourceRefs 是以逗号分隔的引用来源列表。
	// SourceRefs is a comma-separated list of source references.
	SourceRefs string `json:"source_refs,omitempty" yaml:"source_refs,omitempty"`
	// CreatedAt 是节点的创建时间（不参与 YAML 序列化）。
	// CreatedAt is the creation timestamp (excluded from YAML serialization).
	CreatedAt time.Time `json:"created_at" yaml:"-"`
	// UpdatedAt 是节点的最近更新时间（不参与 YAML 序列化）。
	// UpdatedAt is the last-updated timestamp (excluded from YAML serialization).
	UpdatedAt time.Time `json:"updated_at" yaml:"-"`
	// FileSlug 是 shared 节点 primary 文件的可读 slug（用于 _shared/<domain>/<slug>.md）。
	// 首次创建时由 LLM 生成，之后不可变（同 UUID 锚点逻辑）。
	// FileSlug is a human-readable slug for the shared node's primary file path.
	// Generated by LLM on first creation, immutable thereafter (like the UUID anchor).
	FileSlug string `json:"file_slug,omitempty" yaml:"file_slug,omitempty"`
}

// ——————————————————————————————————————————————————————————————————————————————
// Edge — 知识图谱边
// ——————————————————————————————————————————————————————————————————————————————

// Edge 表示知识图谱中的一条有向边，对应数据库 edges 表的一行。
// Edge represents a directed edge in the knowledge graph,
// corresponding to one row in the database edges table.
type Edge struct {
	// ID 是边的内部自增 ID（不参与 YAML 序列化）。
	// ID is the internal auto-increment ID (excluded from YAML serialization).
	ID int64 `json:"id" yaml:"-"`
	// SourceID 是边起点的节点 ID。
	// SourceID is the node ID at the source of the edge.
	SourceID string `json:"source_id" yaml:"source_id"`
	// TargetID 是边终点的节点 ID。
	// TargetID is the node ID at the target of the edge.
	TargetID string `json:"target_id" yaml:"target_id"`
	// Kind 表示边的语义关系类型。
	// Kind indicates the semantic relationship type of the edge.
	Kind RelationKind `json:"kind" yaml:"kind"`
	// Description 是对这条关系的描述。
	// Description is a description of this relationship.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	// Properties 是以 JSON 字符串存储的边附加属性。
	// Properties is a JSON string containing additional edge properties.
	Properties string `json:"properties,omitempty" yaml:"properties,omitempty"`
	// Provenance 指示这条边数据的来源方式。
	// Provenance indicates how the edge data was sourced.
	Provenance Provenance `json:"provenance" yaml:"provenance"`
	// Confidence 是这条边关系的置信度（0.0 ~ 1.0）。
	// Confidence is the confidence score of this edge relationship (0.0 to 1.0).
	Confidence float64 `json:"confidence" yaml:"confidence"`
	// SourceRefs 是以逗号分隔的引用来源列表。
	// SourceRefs is a comma-separated list of source references.
	SourceRefs string `json:"source_refs,omitempty" yaml:"source_refs,omitempty"`
	// Bidirectional 表示该关系是否为双向关系（1 为是，0 为否）。
	// Bidirectional indicates whether the relationship is bidirectional (1 = yes, 0 = no).
	Bidirectional int `json:"bidirectional" yaml:"bidirectional"`
	// Cardinality 表示该关系的基数（如 "1:1", "1:N", "M:N"）。
	// Cardinality indicates the cardinality of the relationship (e.g., "1:1", "1:N", "M:N").
	Cardinality string `json:"cardinality,omitempty" yaml:"cardinality,omitempty"`
	// CreatedAt 是边的创建时间（不参与 YAML 序列化）。
	// CreatedAt is the creation timestamp (excluded from YAML serialization).
	CreatedAt time.Time `json:"created_at" yaml:"-"`
}

// ——————————————————————————————————————————————————————————————————————————————
// Subgraph — BFS 图遍历返回结果
// ——————————————————————————————————————————————————————————————————————————————

// Subgraph 是 BFS 图遍历的返回结果，包含一组节点和它们之间的边。
// Subgraph is the result of a BFS graph traversal, containing a set of nodes
// and the edges between them.
type Subgraph struct {
	// Nodes 是子图中包含的所有节点，以节点 ID 为键的映射。
	// Nodes contains all nodes in the subgraph, keyed by node ID.
	Nodes map[string]*Node `json:"nodes"`
	// Edges 是子图中包含的所有边。
	// Edges contains all edges in the subgraph.
	Edges []*Edge `json:"edges"`
}

// ——————————————————————————————————————————————————————————————————————————————
// CrossReference — 跨 Skill 引用
// ——————————————————————————————————————————————————————————————————————————————

// CrossReference 表示从当前实体指向另一个 Skill 中实体的跨域引用。
// CrossReference represents a cross-skill reference from the current entity
// to an entity in another skill.
type CrossReference struct {
	// ID 是交叉引用的内部自增 ID（不参与 YAML 序列化）。
	// ID is the internal auto-increment ID (excluded from YAML serialization).
	ID int64 `json:"id" yaml:"-"`
	// SourceEntity 是源实体名称 / ID。
	// SourceEntity is the name/ID of the source entity.
	SourceEntity string `json:"source_entity" yaml:"source_entity"`
	// TargetEntity 是目标实体名称 / ID。
	// TargetEntity is the name/ID of the target entity.
	TargetEntity string `json:"target_entity" yaml:"target_entity"`
	// TargetNodeID 是目标实体在知识图谱中的节点 ID（可选）。
	// TargetNodeID is the node ID of the target entity in the knowledge graph (optional).
	TargetNodeID string `json:"target_node_id,omitempty" yaml:"target_node_id,omitempty"`
	// Kind 表示该交叉引用的关系类型。
	// Kind indicates the relationship type of the cross-reference.
	Kind RelationKind `json:"kind" yaml:"kind"`
	// Reason 是该交叉引用存在的原因说明。
	// Reason explains why the cross-reference exists.
	Reason string `json:"reason" yaml:"reason"`
	// ResolutionStatus 表示该交叉引用是否已处理。
	// ResolutionStatus indicates whether the cross-reference has been resolved.
	ResolutionStatus ResolutionStatus `json:"resolution_status" yaml:"resolution_status"`
	// CreatedAt 是交叉引用的创建时间（不参与 YAML 序列化）。
	// CreatedAt is the creation timestamp (excluded from YAML serialization).
	CreatedAt time.Time `json:"created_at" yaml:"-"`
}

// ——————————————————————————————————————————————————————————————————————————————
// ConflictReport — 同名概念冲突报告
// ——————————————————————————————————————————————————————————————————————————————

// ConflictReport 表示因不同来源对同名概念给出不一致定义而产生的冲突报告。
// ConflictReport represents a conflict report generated when different sources
// provide inconsistent definitions for a concept with the same name.
type ConflictReport struct {
	// ID 是冲突报告的内部自增 ID（不参与 YAML 序列化）。
	// ID is the internal auto-increment ID (excluded from YAML serialization).
	ID int64 `json:"id" yaml:"-"`
	// EntityName 是冲突涉及的实体 / 概念名称。
	// EntityName is the name of the entity/concept involved in the conflict.
	EntityName string `json:"entity_name" yaml:"entity_name"`
	// ConflictingSources 是冲突来源列表（以逗号分隔或其他格式）。
	// ConflictingSources is a list of conflicting sources (comma-separated or other format).
	ConflictingSources string `json:"conflicting_sources" yaml:"conflicting_sources"`
	// ResolutionStatus 表示冲突是否已解决。
	// ResolutionStatus indicates whether the conflict has been resolved.
	ResolutionStatus ResolutionStatus `json:"resolution_status" yaml:"resolution_status"`
	// ResolutionNote 是冲突解决的备注说明（可选）。
	// ResolutionNote is an optional note describing how the conflict was resolved.
	ResolutionNote string `json:"resolution_note,omitempty" yaml:"resolution_note,omitempty"`
	// ResolvedBy 是解决该冲突的用户标识（可选）。
	// ResolvedBy is the identifier of the user who resolved the conflict (optional).
	ResolvedBy string `json:"resolved_by,omitempty" yaml:"resolved_by,omitempty"`
	// CreatedAt 是冲突报告的创建时间（不参与 YAML 序列化）。
	// CreatedAt is the creation timestamp (excluded from YAML serialization).
	CreatedAt time.Time `json:"created_at" yaml:"-"`
}

// ——————————————————————————————————————————————————————————————————————————————
// CrossKGLink — 跨 KG 链接（外部知识图谱引用）
// ——————————————————————————————————————————————————————————————————————————————

// CrossKGLink 表示从当前知识图谱指向另一个知识图谱中实体的外部链接。
// 当 cross_reference 的目标无法在当前数据库中解析时，自动标记为 external_kg。
//
// CrossKGLink represents an external link from the current knowledge graph
// to an entity in another knowledge graph. When a cross_reference target cannot
// be resolved in the current database, it is automatically marked as external_kg.
type CrossKGLink struct {
	// FromEntity 是源实体名称 / ID（在当前 KG 中）。
	// FromEntity is the name/ID of the source entity (in the current KG).
	FromEntity string `json:"from_entity"`
	// ToKg 是目标知识图谱的名称。
	// ToKg is the name of the target knowledge graph.
	ToKg string `json:"to_kg"`
	// ToEntity 是目标实体名称 / ID（在目标 KG 中）。
	// ToEntity is the name/ID of the target entity (in the target KG).
	ToEntity string `json:"to_entity"`
	// Kind 表示该链接的关系类型。
	// Kind indicates the relationship type of the cross-KG link.
	Kind RelationKind `json:"kind"`
	// Reason 是该跨 KG 链接的原因说明（可选）。
	// Reason explains why this cross-KG link exists (optional).
	Reason string `json:"reason,omitempty"`
	// CreatedAt 是链接的创建时间。
	// CreatedAt is the creation timestamp.
	CreatedAt time.Time `json:"created_at,omitempty"`
}
